# Generated by Django 5.0.3 on 2024-03-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_selector_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
